Repository dude613/avoda-be, pull requests merged in 2025-03, with the labels that each got.

#1 Add Sentry error monitoring and performance tracking
  index.js
  instrument.js
  package.json
  sample.env
Labels: Review effort 2/5

#3 Chore/constants
  Components/MailerComponents/ForgotTemplate.js
  Components/MailerComponents/OTPTemplate.js
  Components/MailerComponents/SendOTPMail.js
  Components/MailerComponents/Transporter.js
  Components/MailerComponents/VerifyEmail.js
  Components/Transporter.js
  Constants/AppConstants.js
  Constants/MailerConstants.js
  Constants/UserConstants.js
  Controller/User/ForgotPassword.js
  Controller/User/Login.js
  Controller/User/Register.js
  Controller/User/VerifyOtp.js
  Routes/Auth/AuthRoute.js
  index.js
  package.json
Labels: Review effort 3/5

#4 Main
  Components/MailerComponents/SendInvitation.js
  Components/MailerComponents/SendOTPMail.js
  Components/Uploads/Multer.js
  Components/Uploads/UploadImage.js
  Components/uploads/1742191936643-a6d5ea5a25ca.png
  Controller/Organization/AddTeamMember.js
  Controller/Organization/CreateOrganization.js
  Controller/User/ForgotPassword.js
  Controller/User/Login.js
  Controller/User/Register.js
  Controller/User/VerifyOtp.js
  Model/OrganizationSchema.js
  Model/TeamMemberSchema.js
  Model/UserOtpSchema.js
  Model/UserSchema.js
  Routes/Api.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
  index.js
  package.json
  sample.env
Labels: Review effort 4/5

#7 Add basic CI/PR check with Jest testing setup
  .github/workflows/basic-check.yml
  __tests__/instrument.test.js
  instrument.js
  jest.config.js
  package.json
Labels: Review effort 1/5

#10 Feat/get google ids for oauth
  Components/ConnectDatabase.js
  Controller/User/Login.js
  Controller/User/UserProfile.js
  Routes/Api.js
  Routes/Auth/AuthRoute.js
Labels: Review effort 3/5

#15 AVO-116, Create Soft delete user apis
  Components/Uploads/UploadImage.js
  Controller/Organization/AddTeamMember.js
  Controller/User/UserProfile.js
  Model/TeamMemberSchema.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
Labels: Review effort 2/5
