Repository dude613/avoda-be, pull requests merged in 2025-04, with the labels that each got.

#20 Fix PR review comment detection criteria
  prreview.py
Labels: Review effort 1/5

#21 update error handling on auth process
  Components/MailerComponents/ForgotTemplate.js
  Components/MailerComponents/SendInvitation.js
  Components/MailerComponents/SendOTPMail.js
  Constants/UserConstants.js
  Controller/User/Register.js
  Controller/User/VerifyOtp.js
Labels: Review effort 2/5

#23 Created deploy-staging.yml
  .github/workflows/deploy-staging.yml
Labels: Review effort 2/5

#25 Update deploy-staging.yml
  .github/workflows/deploy-staging.yml
Labels: Review effort 1/5

#26 Update deploy-staging.yml
  .github/workflows/deploy-staging.yml
Labels: Review effort 1/5

#29 Create deploy-prod.yml
  .github/workflows/deploy-prod.yml
Labels: Review effort 2/5

#27 Feat/avo 173/validation for cuncurrent timers
  Controller/Timer/index.js
  Controller/User/VerifyOtp.js
  Model/Timer.js
  Routes/Api.js
  Routes/Timer/index.js
  index.js
  middleware/authMiddleware.js
  middleware/timerValidation.js
  pnpm-lock.yaml
  services/webSocketService.js
Labels: Review effort 3/5

#31 update main
  .github/workflows/.ai-pr-review.yml
  .github/workflows/deploy-staging.yml
  .gitignore
  .vscode/settings.json
  Components/ConnectDatabase.js
  Components/MailerComponents/ForgotTemplate.js
  Components/MailerComponents/SendInvitation.js
  Components/MailerComponents/SendOTPMail.js
  Components/MailerComponents/Transporter.js
  Components/Uploads/UploadImage.js
  Components/VerifyAccessToken.js
  Constants/AppConstants.js
  Constants/MailerConstants.js
  Constants/OrganizationBulk.js
  Constants/UserConstants.js
  Controller/Organization/AddTeamMember.js
  Controller/Organization/CreateOrganization.js
  Controller/Timer/index.js
  Controller/User/ForgotPassword.js
  Controller/User/Login.js
  Controller/User/Register.js
  Controller/User/UserProfile.js
  Controller/User/VerifyOtp.js
  Model/OrganizationSchema.js
  Model/TeamMemberSchema.js
  Model/Timer.js
  Model/UserSchema.js
  Routes/Api.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
  Routes/Timer/index.js
  env.sample
  index.js
  instrument.js
  middleware/authMiddleware.js
  middleware/timerValidation.js
  package.json
  pnpm-lock.yaml
  prreview.py
  services/webSocketService.js
Labels: Review effort 4/5

#35 updates for role based login
  Constants/UserConstants.js
  Controller/Organization/AddTeamMember.js
  Controller/Organization/CreateOrganization.js
  Controller/User/ForgotPassword.js
  Controller/User/Login.js
  Controller/User/Register.js
  Controller/User/UserProfile.js
  Controller/User/VerifyOtp.js
  Model/UserSchema.js
  package.json
Labels: Review effort 3/5

#36 Bug fix/forgot email
  Components/MailerComponents/SendOTPMail.js
  Constants/MailerConstants.js
  Constants/UserConstants.js
  Controller/User/ForgotPassword.js
  Controller/User/Register.js
  Controller/User/UserProfile.js
  Controller/User/VerifyOtp.js
Labels: Review effort 2/5

#37 updated constants for sending invitations
  Components/MailerComponents/SendInvitation.js
Labels: Review effort 1/5

#38 updates in user profile
  Constants/UserConstants.js
  Controller/Organization/AddTeamMember.js
  Controller/User/ForgotPassword.js
  Controller/User/Logout.js
  Controller/User/UserProfile.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
Labels: Review effort 3/5

#40 fixed typo issue
  Routes/Organization/Organization.js
Labels: Review effort 1/5

#41 Update deploy-staging.yml
  .github/workflows/deploy-staging.yml
Labels: Review effort 2/5

#42 update
  .github/workflows/deploy-staging.yml
  Components/MailerComponents/SendInvitation.js
  Components/MailerComponents/SendOTPMail.js
  Constants/MailerConstants.js
  Constants/UserConstants.js
  Controller/Organization/AddTeamMember.js
  Controller/Organization/CreateOrganization.js
  Controller/User/ForgotPassword.js
  Controller/User/Login.js
  Controller/User/Logout.js
  Controller/User/Register.js
  Controller/User/UserProfile.js
  Controller/User/VerifyOtp.js
  Model/UserSchema.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
  package.json
Labels: Review effort 4/5

#43 Add GitHub workflow for backend deployment to EC2
  .github/workflows/deploy-be-test.yml
Labels: Review effort 2/5

#44 Update deploy-be-test.yml
  .github/workflows/deploy-be-test.yml
Labels: Review effort 1/5

#45 New be test
  .github/workflows/deploy-be-test.yml
Labels: Review effort 2/5

#48 Delete .github/workflows/deploy-staging.yml
  .github/workflows/deploy-staging.yml
Labels: Review effort 1/5

#49 Delete .github/workflows/deploy-prod.yml
  .github/workflows/deploy-prod.yml
Labels: Review effort 1/5

#51 fix forgot password issue
  Components/MailerComponents/ForgotTemplate.js
  Controller/User/ForgotPassword.js
  Model/UserSchema.js
  uploads/1743844156718-c3781611ad95.jpg
Labels: Review effort 2/5

#52 fix forgot password bcrypt issue
  Controller/User/ForgotPassword.js
Labels: Review effort 2/5

#54 fix forgot password issue
  Constants/UserConstants.js
  Controller/User/ForgotPassword.js
Labels: Review effort 1/5

#46 feat: total migration from mongoose-mongodb to postgres-prisma
  .gitignore
  Components/ConnectDatabase.js
  Components/VerifyAccessToken.js
  Constants/AppConstants.js
  Constants/UserConstants.js
  Controller/Organization/AddTeamMember.js
  Controller/Organization/AddTeamMember.ts
  Controller/Organization/CreateOrganization.js
  Controller/Organization/CreateOrganization.ts
  Controller/Timer/index.js
  Controller/Timer/index.ts
  Controller/User/ForgotPassword.js
  Controller/User/ForgotPassword.ts
  Controller/User/Login.js
  Controller/User/Login.ts
  Controller/User/Logout.js
  Controller/User/Logout.ts
  Controller/User/Register.js
  Controller/User/Register.ts
  Controller/User/UserProfile.js
  Controller/User/UserProfile.ts
  Controller/User/VerifyOtp.js
  Controller/User/VerifyOtp.ts
  Dockerfile
  Model/OrganizationSchema.js
  Model/TeamMemberSchema.js
  Model/Timer.js
  Model/UserOtpSchema.js
  Model/UserSchema.js
  Routes/Api.js
  Routes/Auth/AuthRoute.js
  Routes/Organization/Organization.js
  Routes/Timer/index.js
  docker-compose.yml
  env.sample
  index.js
  middleware/authMiddleware.js
  middleware/timerValidation.js
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250404112825_add_auth_org_timer_tables/migration.sql
  prisma/migrations/20250404120446_add_unique_constraint_to_user_id/migration.sql
  prisma/migrations/20250404133328_updated_organization_model/migration.sql
  prisma/migrations/20250404140152_updated_team_member_schema/migration.sql
  prisma/migrations/20250404220629_added_missing_relation_definition_and_formatted_code/migration.sql
  prisma/migrations/20250405092249_added_last_login_at_to_user_schema/migration.sql
  prisma/migrations/20250406062112_updated_user_schema/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  tsconfig.json
  types/organization.types.ts
  types/timer.types.ts
  types/user.types.ts
Labels: Review effort 4/5

#56 Add Sentry error tracking and update .gitignore
  .gitignore
  Components/VerifyAccessToken.ts
Labels: Review effort 2/5

#58 Ai docs
  .github/workflows/build.yml
Labels: Review effort 2/5

#59 Avi/migration from js to ts
  .gitignore
  Components/MailerComponents/SendOTPMail.ts
  Components/MailerComponents/Transporter.ts
  Components/VerifyAccessToken.ts
  Controller/Organization/AddTeamMember.ts
  Controller/Organization/CreateOrganization.ts
  Controller/Timer/index.ts
  Controller/User/ForgotPassword.ts
  Controller/User/Login.ts
  Controller/User/Logout.ts
  Controller/User/Register.ts
  Controller/User/UserProfile.ts
  Controller/User/VerifyOtp.ts
  Routes/Organization/Organization.ts
  Routes/Timer/index.ts
  instrument.d.ts
  instrument.ts
  middleware/authMiddleware.ts
  middleware/timerValidation.ts
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250404120446_add_unique_constraint_to_user_id/migration.sql
  prisma/migrations/20250404133328_updated_organization_model/migration.sql
  prisma/migrations/20250404140152_updated_team_member_schema/migration.sql
  prisma/migrations/20250404220629_added_missing_relation_definition_and_formatted_code/migration.sql
  prisma/migrations/20250405092249_added_last_login_at_to_user_schema/migration.sql
  prisma/migrations/20250406062112_updated_user_schema/migration.sql
  prisma/migrations/20250408025805_init/migration.sql
  prisma/migrations/20250408040241_updated_otp_schema/migration.sql
  prisma/migrations/20250408053943_updated_otp_in_op_schema_from_int_to_string/migration.sql
  prisma/schema.prisma
  services/webSocketService.ts
  types/organization.types.ts
  types/user.types.ts
  utils/asyncHandler.ts
Labels: Review effort 4/5

#60 Oluwadamilare321/avo 192 create endpoint to pause and resume timer and integrate it
  .DS_Store
  Controller/Organization/AddTeamMember.ts
  Controller/Timer/index.ts
  Controller/User/Login.ts
  Controller/User/Register.ts
  Controller/User/UserProfile.ts
  Routes/Timer/index.ts
  instrument.ts
  middleware/timerValidation.ts
  prisma/migrations/20250409184700_added_pause_and_pause_time_to_timer_model/migration.sql
  prisma/migrations/20250410002914_added_total_paused_time_to_timer_schema/migration.sql
  prisma/schema.prisma
  services/webSocketService.ts
  types/timer.types.ts
  types/user.types.ts
  utils/asyncHandler.ts
Labels: Review effort 4/5

#62 Sort and filter functionality, timer notes logic
  .DS_Store
  Controller/Timer/index.ts
  Routes/Timer/index.ts
  middleware/validateTimerNote.ts
  prisma/migrations/20250411063738_added_note_to_timer_schema/migration.sql
  prisma/migrations/20250411143451_changed_character_limit_from_500_to_200_ontimer_note/migration.sql
  prisma/schema.prisma
  types/timer.types.ts
  uploads/images/images-1744361623050-101769088.jpg
Labels: Review effort 3/5

#67 Delete .github/workflows/build.yml
  .github/workflows/build.yml
Labels: Review effort 1/5

#70 Oluwadamilare321/avo 195 create endpoints for clients
  Controller/Client/ClientController.ts
  Routes/Api.ts
  Routes/Client/ClientRoute.ts
  prisma/migrations/20250416075427_added_client_to_schema/migration.sql
  prisma/migrations/20250416203100_updated_client_schema/migration.sql
  prisma/schema.prisma
  types/client.types.ts
Labels: Review effort 3/5

#75 fix CORS error (#74)
  .DS_Store
  .github/workflows/.ai-pr-review.yml
  .github/workflows/build.yml
  .github/workflows/deployment.yml
  Components/MailerComponents/Transporter.ts
  Controller/Client/ClientController.ts
  Controller/Organization/AddTeamMember.ts
  Controller/Organization/CreateOrganization.ts
  Controller/Permissions/index.ts
  Controller/Project/Project.ts
  Controller/Task/Task.ts
  Controller/Timer/index.ts
  Routes/Api.ts
  Routes/Client/ClientRoute.ts
  Routes/Permissions/permissions.ts
  Routes/Project/Project.ts
  Routes/Task/task.ts
  Routes/Timer/index.ts
  commit-hygiene.md
  index.ts
  middleware/permissionMiddleware.ts
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250422133833_added_permissions/migration.sql
  prisma/migrations/20250423003813_added_archived_status_to_user_schema/migration.sql
  prisma/migrations/20250423115839_added_client_project_tasks_assignment_to_schema/migration.sql
  prisma/schema.prisma
  prreview.py
  scripts/seedPermissions.ts
  types/client.types.ts
  utils/asyncHandler.ts
Labels: Review effort 4/5

#79 Minor updates on tasks and billing rate
  Controller/Task/Task.ts
  prisma/migrations/20250429101922_billing_rate_type_updated/migration.sql
  prisma/schema.prisma
Labels: Review effort 2/5
